# -*- coding: utf-8 -*-
"""LR_1_task_1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_80Bfeva8Ox8vUhbfipRTTIrMb7MfJ5

**2.1.5. Кодування міток**
"""

import numpy as np
from sklearn import preprocessing

input_labels = ['red', 'black', 'red', 'green', 'black', 'yellow', 'white']

# Створення об'єкта кодування міток та навчання його
encoder = preprocessing.LabelEncoder()
encoder.fit(input_labels)

# Виведення відображення слів на числа
print("\nLabel mapping:")
for i, item in enumerate(encoder.classes_):
    print(item, '-->', i)

# Перетворення набору випадково впорядкованих міток
test_labels = ['green', 'red', 'black']
encoded_values = encoder.transform(test_labels)
print("\nLabels =", test_labels)
print("Encoded values =", list(encoded_values))

# Декодування випадкового набору чисел
encoded_values = [3, 0, 4, 1]
decoded_list = encoder.inverse_transform(encoded_values)
print("\nEncoded values =", encoded_values)
print("Decoded labels =", list(decoded_list))