# -*- coding: utf-8 -*-
"""R_1_task_6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XeS3JNteYWTCzjhr4lUJFmdW3IXBSC6X

Завдання 2.6. Розробіть програму класифікації даних
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, cross_val_score
from utilities import visualize_classifier

input_file = 'data_multivar_nb.txt'
data = np.loadtxt(input_file, delimiter=',')
X, y = data[:, :-1], data[:, -1]

# 2. Розбиття даних на навчальний та тестовий набори
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Створення та навчання класифікатора SVM
classifier_svm = SVC(kernel='linear', gamma='auto')
classifier_svm.fit(X_train, y_train)

# 4. Прогнозування та оцінка якості на тестових даних
y_test_pred = classifier_svm.predict(X_test)
accuracy = 100.0 * (y_test == y_test_pred).sum() / X_test.shape[0]
print("Accuracy of SVM classifier on test data =", round(accuracy, 2), "%")

# 5. Візуалізація результатів класифікації
visualize_classifier(classifier_svm, X_test, y_test)

# 6. Оцінка якості за допомогою перехресної перевірки (cross-validation)
print("\n--- Cross-validation results for SVM ---")
num_folds = 3
accuracy_values_svm = cross_val_score(classifier_svm, X, y, scoring='accuracy', cv=num_folds)
precision_values_svm = cross_val_score(classifier_svm, X, y, scoring='precision_weighted', cv=num_folds)
recall_values_svm = cross_val_score(classifier_svm, X, y, scoring='recall_weighted', cv=num_folds)
f1_values_svm = cross_val_score(classifier_svm, X, y, scoring='f1_weighted', cv=num_folds)

print("Accuracy (SVM): " + str(round(100 * accuracy_values_svm.mean(), 2)) + "%")
print("Precision (SVM): " + str(round(100 * precision_values_svm.mean(), 2)) + "%")
print("Recall (SVM): " + str(round(100 * recall_values_svm.mean(), 2)) + "%")
print("F1 (SVM): " + str(round(100 * f1_values_svm.mean(), 2)) + "%")

# 7. Збір результатів Naive Bayes з попереднього завдання для порівняння
accuracy_nb = 99.75
precision_nb = 99.76
recall_nb = 99.75
f1_nb = 99.75
print("\n--- Naive Bayes results for comparison ---")
print(f"Accuracy (Naive Bayes): {accuracy_nb}%")
print(f"Precision (Naive Bayes): {precision_nb}%")
print(f"Recall (Naive Bayes): {recall_nb}%")
print(f"F1 (Naive Bayes): {f1_nb}%")